//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Muxa
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Здание.
    /// </summary>
    // *** Start programmer edit section *** (Home CustomAttributes)

    // *** End programmer edit section *** (Home CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("HomeE", new string[] {
            "Название as \'Название\'",
            "Адрес as \'Адрес\'",
            "Долгота as \'Долгота\'",
            "Широта as \'Широта\'",
            "ГородID as \'Город ID\'",
            "IDИдентификатор as \'I d идентификатор\'",
            "City as \'City\'",
            "City.Название as \'Название\'"}, Hidden=new string[] {
            "City.Название"})]
    [MasterViewDefineAttribute("HomeE", "City", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [View("HomeL", new string[] {
            "Название as \'Название\'",
            "Адрес as \'Адрес\'",
            "Долгота as \'Долгота\'",
            "Широта as \'Широта\'",
            "ГородID as \'Город ID\'",
            "IDИдентификатор as \'I d идентификатор\'",
            "City.Название as \'Название\'"})]
    [View("ЗданиеE", new string[] {
            "Название as \'Название\'",
            "Адрес as \'Адрес\'",
            "Долгота as \'Долгота\'",
            "Широта as \'Широта\'",
            "ГородID as \'Город ID\'",
            "IDИдентификатор as \'I d идентификатор\'"})]
    [View("ЗданиеL", new string[] {
            "Название as \'Название\'",
            "Адрес as \'Адрес\'",
            "Долгота as \'Долгота\'",
            "Широта as \'Широта\'",
            "ГородID as \'Город ID\'",
            "IDИдентификатор as \'I d идентификатор\'"})]
    public class Home : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private string fАдрес;
        
        private double fДолгота;
        
        private double fШирота;
        
        private int fГородID;
        
        private int fIDИдентификатор;
        
        private IIS.Muxa.City fCity;
        
        // *** Start programmer edit section *** (Home CustomMembers)

        // *** End programmer edit section *** (Home CustomMembers)

        
        /// <summary>
        /// IDИдентификатор.
        /// </summary>
        // *** Start programmer edit section *** (Home.IDИдентификатор CustomAttributes)

        // *** End programmer edit section *** (Home.IDИдентификатор CustomAttributes)
        public virtual int IDИдентификатор
        {
            get
            {
                // *** Start programmer edit section *** (Home.IDИдентификатор Get start)

                // *** End programmer edit section *** (Home.IDИдентификатор Get start)
                int result = this.fIDИдентификатор;
                // *** Start programmer edit section *** (Home.IDИдентификатор Get end)

                // *** End programmer edit section *** (Home.IDИдентификатор Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Home.IDИдентификатор Set start)

                // *** End programmer edit section *** (Home.IDИдентификатор Set start)
                this.fIDИдентификатор = value;
                // *** Start programmer edit section *** (Home.IDИдентификатор Set end)

                // *** End programmer edit section *** (Home.IDИдентификатор Set end)
            }
        }
        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Home.Адрес CustomAttributes)

        // *** End programmer edit section *** (Home.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Home.Адрес Get start)

                // *** End programmer edit section *** (Home.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Home.Адрес Get end)

                // *** End programmer edit section *** (Home.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Home.Адрес Set start)

                // *** End programmer edit section *** (Home.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Home.Адрес Set end)

                // *** End programmer edit section *** (Home.Адрес Set end)
            }
        }
        
        /// <summary>
        /// ГородID.
        /// </summary>
        // *** Start programmer edit section *** (Home.ГородID CustomAttributes)

        // *** End programmer edit section *** (Home.ГородID CustomAttributes)
        public virtual int ГородID
        {
            get
            {
                // *** Start programmer edit section *** (Home.ГородID Get start)

                // *** End programmer edit section *** (Home.ГородID Get start)
                int result = this.fГородID;
                // *** Start programmer edit section *** (Home.ГородID Get end)

                // *** End programmer edit section *** (Home.ГородID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Home.ГородID Set start)

                // *** End programmer edit section *** (Home.ГородID Set start)
                this.fГородID = value;
                // *** Start programmer edit section *** (Home.ГородID Set end)

                // *** End programmer edit section *** (Home.ГородID Set end)
            }
        }
        
        /// <summary>
        /// Долгота.
        /// </summary>
        // *** Start programmer edit section *** (Home.Долгота CustomAttributes)

        // *** End programmer edit section *** (Home.Долгота CustomAttributes)
        public virtual double Долгота
        {
            get
            {
                // *** Start programmer edit section *** (Home.Долгота Get start)

                // *** End programmer edit section *** (Home.Долгота Get start)
                double result = this.fДолгота;
                // *** Start programmer edit section *** (Home.Долгота Get end)

                // *** End programmer edit section *** (Home.Долгота Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Home.Долгота Set start)

                // *** End programmer edit section *** (Home.Долгота Set start)
                this.fДолгота = value;
                // *** Start programmer edit section *** (Home.Долгота Set end)

                // *** End programmer edit section *** (Home.Долгота Set end)
            }
        }
        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Home.Название CustomAttributes)

        // *** End programmer edit section *** (Home.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Home.Название Get start)

                // *** End programmer edit section *** (Home.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Home.Название Get end)

                // *** End programmer edit section *** (Home.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Home.Название Set start)

                // *** End programmer edit section *** (Home.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Home.Название Set end)

                // *** End programmer edit section *** (Home.Название Set end)
            }
        }
        
        /// <summary>
        /// Широта.
        /// </summary>
        // *** Start programmer edit section *** (Home.Широта CustomAttributes)

        // *** End programmer edit section *** (Home.Широта CustomAttributes)
        public virtual double Широта
        {
            get
            {
                // *** Start programmer edit section *** (Home.Широта Get start)

                // *** End programmer edit section *** (Home.Широта Get start)
                double result = this.fШирота;
                // *** Start programmer edit section *** (Home.Широта Get end)

                // *** End programmer edit section *** (Home.Широта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Home.Широта Set start)

                // *** End programmer edit section *** (Home.Широта Set start)
                this.fШирота = value;
                // *** Start programmer edit section *** (Home.Широта Set end)

                // *** End programmer edit section *** (Home.Широта Set end)
            }
        }
        
        /// <summary>
        /// Здание.
        /// </summary>
        // *** Start programmer edit section *** (Home.City CustomAttributes)

        // *** End programmer edit section *** (Home.City CustomAttributes)
        [PropertyStorage(new string[] {
                "City"})]
        [NotNull()]
        public virtual IIS.Muxa.City City
        {
            get
            {
                // *** Start programmer edit section *** (Home.City Get start)

                // *** End programmer edit section *** (Home.City Get start)
                IIS.Muxa.City result = this.fCity;
                // *** Start programmer edit section *** (Home.City Get end)

                // *** End programmer edit section *** (Home.City Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Home.City Set start)

                // *** End programmer edit section *** (Home.City Set start)
                this.fCity = value;
                // *** Start programmer edit section *** (Home.City Set end)

                // *** End programmer edit section *** (Home.City Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "HomeE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View HomeE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("HomeE", typeof(IIS.Muxa.Home));
                }
            }
            
            /// <summary>
            /// "HomeL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View HomeL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("HomeL", typeof(IIS.Muxa.Home));
                }
            }
            
            /// <summary>
            /// "ЗданиеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗданиеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗданиеE", typeof(IIS.Muxa.Home));
                }
            }
            
            /// <summary>
            /// "ЗданиеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗданиеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗданиеL", typeof(IIS.Muxa.Home));
                }
            }
        }
    }
}
